### ISSUE TITLE
Заменить картинки на главной странице UI для пользователей  

### ISSUE THREAD

**Issue by YaroslavGritsishin** [ChristianRekfild/YourRest#142]
Для Главной страницы UI для пользователей создать сервис для получения картинок от MINIO
Вставить полученные данные до момента отрисовки компонента.

**Comment by liliaretsia** [comment]
1. Добавить 3 колонки (description, photoUrl, isFavorite true/false (любимый город)). В методе, который отдает города, добавить эти поля + фильтр isFavorite
2. Сиды дополнить
3. Метод загрузки фото для города
4. Отобразить данные в ui
