### ISSUE TITLE
Создать метод регистрации отельера api/operator/registration/request

### ISSUE THREAD

**Issue by MKSharpDev** [ChristianRekfild/YourRest#30]
1. api/operator/registration/request
Method: POST
Body:
{
  "company_name": "string",
  "email": "string",
  "phone": "string"
}

Errors: 400 (Bad Request)

**Comment by liliaretsia** [comment]
Операторы могут самостоятельно регистрироваться в Keycloak.
При создании realm нужно включить функцию самостоятельной регистрации
