### ISSUE TITLE
Метод создания отельером менеджера api/operator/user

### ISSUE THREAD

**Issue by MKSharpDev** [ChristianRekfild/YourRest#31]
2. api/operator/user
Method: POST
Body:
{
  "lastname": "string",
 "firstname": "string",
 "middlename": "string",
  "dob": "date",
  "login":  "string",
  "password":  "string",
 "role_id":  "number",
 "is_active":  "boolean",
}

**Comment by liliaretsia** [comment]
Юзера создаем из токена авторизации. Реализация в задаче по создание сервиса аутентификации
