### ISSUE TITLE
api/operator/accommodation

### ISSUE THREAD

**Issue by MKSharpDev** [ChristianRekfild/YourRest#35]
7. api/operator/accommodation
Method: POST, PUT(api/operator/accommodation/{accommodatioId})
Body:
{
  "name": "string",
 "bank_account": "string",
 "description": "string",
 "accommodation_type": "number",
}

Errors: 400 (Bad Request), 404 (Not Found)

**Comment by TarantasGitHub** [comment]
Что это такое?

**Comment by liliaretsia** [comment]
Это метод добавления самого отеля, и метод редактирования отеля по айди.
