### ISSUE TITLE
Создать метод возвращающий список доп. услуг в номере  api/operator/roomFacility

### ISSUE THREAD

**Issue by MKSharpDev** [ChristianRekfild/YourRest#39]
16. api/operator/roomFacility Возвращает список доп. услуг в номере (minibar, locker, jacussi)//создает доп услугу
Method: GET, POST
Body for POST:
{
  "name": "string",
  "description": "string"
}

Errors: 400 (Bad Request)

**Comment by liliaretsia** [comment]
facility_name уникальный, надо выбрасывать 422 unprocessible entity, если пытаются создать еще запись с таким именем.

**Comment by liliaretsia** [comment]
Метод нужно добавить в проект HotelManagementWebApi, тесты в HotelManagementWebApi.Tests

**Comment by liliaretsia** [comment]
Обсудили 9 октября. Решили делать такие методы в этой задаче: 

**GET api/facilities -** 
**POST api/facility**
{
  "name": "wii-fi"
}
**PUT api/facility/id}**
{
  "name": "wii-fi"
}
**DELETE api/facility/{id}**
