### ISSUE TITLE
api/operator/roomRateType

### ISSUE THREAD

**Issue by MKSharpDev** [ChristianRekfild/YourRest#40]
19. api/operator/roomRateType
Method: GET, POST
Body for POST:
{
  "type_name": "string",
  "description": "string"
}

Errors: 400 (Bad Request)

**Comment by TarantasGitHub** [comment]
Что это такое?

**Comment by liliaretsia** [comment]
Эту задачу можем закрыть.
У отелей бывают разные цены на один и тот же период, и на одну и ту же комнату.
Например, если еще есть квота, в наличии 30 номеров, то одна цена (commitment).
Если квоты нет, и отель по запросу, то другая цена (allotment).

Но в этой системе мы работаем только с комнатами, которые в наличии, поэтому не актуально.
