### ISSUE TITLE
Реализовать апи-метод api/room

### ISSUE THREAD

**Issue by liliaretsia** [ChristianRekfild/YourRest#90]
GET api/rooms (уже в мастере)
GET api/rooms/{id}
POST api/rooms (уже в мастере)
{
"name": "test",
"capacity": 1,
.....
}
PUT api/rooms/id}
{
"name": "wii-fi",
.....
}
DELETE api/rooms/{id}

**Comment by YaroslavGritsishin** [comment]
PUT api/rooms/id в маршрут добавлю id комнаты.
